baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Events | Thriving Cities"
buildFuture = true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

# Staticman params
[params.staticman]
endpoint = "https://api.staticman.net/v2/entry"
username = "jSwtch"
repository = "thriving-cities-events"
branch = "master"

